
language: bash

script: true

after_success: ./merge.sh $GIT_USER $GIT_PASS

env:
  global:
  - GIT_COMMITTER_NAME=elmas3-via-TravisCI
  - GIT_COMMITTER_EMAIL=elmas3@users.noreply.github.com
  - GIT_AUTHOR_NAME=elmas3-via-TravisCI
  - GIT_AUTHOR_EMAIL=elmas3@users.noreply.github.com
